# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.5
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Import Export Xlsx or csv file easily
repo_name: Pattern Import Export
repo_slug: pattern-import-export
travis_apt_packages: []
travis_apt_sources: []
